key = "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"
file = "file-xfFe9kHyuV8m1MRDNUgsdlBZ"
assistant_id = "asst_o6ct3M2Ot3sBn56G3U3pqh9S"
thread_id = "thread_5iXWqxm8uiqNBf8MdZUMATnc"

[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
font="sans serif"
textColor="#262730"